wandb_version: 1

__class__:
  desc: null
  value: wandb.sdk.wandb_config.Config
_wandb:
  desc: null
  value:
    cli_version: 0.11.0
    framework: huggingface
    huggingface_version: 4.6.1
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.7.10
    t:
      1:
      - 1
      - 11
      4: 3.7.10
      5: 0.11.0
      6: 4.6.1
      8:
      - 1
      - 3
      - 5
